mybatis:
  type-aliases-package: com.neok.commonSpringboot.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    call-setters-on-nulls: true
#server:
#  port: 80
#  servlet:
#    session:
#      timeout: 24h
#      cookie:
#        max-age: 24h

---
spring:
  profiles: local
  main:
    allow-bean-definition-overriding: true
    
  devtools:
    livereload:
      enabled: true
      
  freemarker:
    cache: false
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.17.14:3306/panda?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: panda
    password: qleldoqtm
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    password: pass
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true 
    
file:
  uploadDir: C:/file_storage
  
mail:
  mailUserName: tirran.dev@gmail.com
  
---
spring:
  profiles: prod
  main:
    allow-bean-definition-overriding: false
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.17.14:3306/panda?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: panda
    password: qleldoqtm
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

file:
  uploadDir: file_storage